### PR TITLE
add unit test and fix for GET with content-type header

### PR DESCRIPTION
**Pull request by ahmad2x4**

### CODE REVIEW

**Comment by ahmad2x4** [comment]
This fix issue #13

**Comment by yakovkhalinsky** [comment]
Thanks @ahmad2x4 adding better test coverage is high on our priority list, especially since we would like to encourage contributions :+1: 

Just one question about this PR. Are you using tabs instead of spaces? Just makes it difficult to see what has changed in the diffs.

**Comment by ahmad2x4** [comment]
No worries @yakovkhalinsky. I think the problem is my line endings. I'm using windows and I think this changes came from the CrLF. I've tried to set my line endings to unix but it seems git didn't pick up

**Comment by yakovkhalinsky** [comment]
No worries, we'll have a look at this over the next day :+1:

**Comment by marcelogo** [comment]
Hey @ahmad2x4 

Thanks for bringing our attention to the headers.

This issue seems to be addressed by #1, which has been merged.

We added some more tests to cover your example.

Additionally, for the moment we do not intend to restrict a GET with a request body (even though most people won't do it).

Thanks for putting the time to make a contribution.

**Pull request closed without merging**
