### PR TITLE
CORS - configurable Access-Control-Allow-Headers

### PR DESCRIPTION
**Pull request by artlogic**
Pull request for issue #101.

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Thanks @artlogic looks good.

My only criticism would be to use `headers` instead of `header` as the argument, as it takes multiple headers :+1: 

Looks like there is a conflict with our master branch, perhaps a rebase onto your branch of our latest master might fix this.

I'll review again once you have fixed the conflicts.

**Comment by artlogic** [comment]
@yakovkhalinsky - I went with `--header` to because of `--method`. Should it acutally be `--methods` too?

Sorry about that conflict - I forget to merge in upstream changes - my fork was a bit old. That'll be fixed shortly.

**Comment by yakovkhalinsky** [comment]
@artlogic ah good point! Let's stick with `--header` then :dart: :+1:

**Comment by artlogic** [comment]
@yakovkhalinsky - should be good now!

**Comment by yakovkhalinsky** [comment]
Looks great! :+1: 

Thanks also for updating the README, arguments module and adding a test :dart:

Will merge shortly

**Pull request merged**
