### PR TITLE
avoid exit in express middleware

### PR DESCRIPTION
**Pull request by openhoat**

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Thanks @openhoat for the PR

I'll get it into the next version in the next day or so :+1:

**Comment by openhoat** [comment]
thanks for your responsiveness !

**Comment by yakovkhalinsky** [comment]
@openhoat just about to look at this

did you mean to close this PR?

**Comment by yakovkhalinsky** [comment]
Merging

**Comment by openhoat** [comment]
0.2.2 &rarr; nice :-)

**Pull request merged**
