### PR TITLE
Use protagonist instead of outdated drafter

### PR DESCRIPTION
**Pull request by ascripcaru**

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
OK, so I'm going to a final 0.1.x release now to NPM, then we can get down to the business of using Node.js 4 and 5 :+1:

**Comment by yakovkhalinsky** [comment]
When I get a chance later today just want to do a final clean up of the CHANGELOG and then I'll do an NPM publish and then I'll up the minor version and then merge this PR :+1:

**Comment by yakovkhalinsky** [comment]
OK looking at this now, 

I'm a little surprised none of our tests failed with these changes.

**Comment by yakovkhalinsky** [comment]
Have locally created a 0.2 branch and have rebased the `dev` branch in your forked repository.

Will be pushing to this branch and just double checking the tests.

Hopefully we'll have this up in the next couple of days :+1:

**Comment by yakovkhalinsky** [comment]
@ascripcaru can you tell me what system you are running? (OS and version)

**Comment by yakovkhalinsky** [comment]
On node.js 0.12.9 (Mac OS X 10.11) I'm getting a segfault when running the API tests

**Comment by yakovkhalinsky** [comment]
there's an upstream dependency on an old version of protagonist in `grunt-blueprint-validator` which will need to be resolved.

ping @marcelogo

**Comment by ascripcaru** [comment]
@yakovkhalinsky I am using OSX el capitan with node 0.12.9 but the tests are not failing. regarding `grunt-blueprint-validator` I raised a pull request there as well.

**Comment by yakovkhalinsky** [comment]
Superseded by PR #110

**Pull request closed without merging**
