### PR TITLE
adding the "--public" flag to allow users to open the drakov server to

### PR DESCRIPTION
**Pull request by obihann**
Adding an optional flag so users can open drakov up to external requests.

### CODE REVIEW

**Comment by obihann** [comment]
One thing that may further enhance this is enabling CORS (https://www.npmjs.com/package/cors) when the user enables the --public flag. I will add that to this pull request tonight.

**Comment by obihann** [comment]
One thing that might further enhance this is CORS support. I thought I found a quick solution however it was designed for express based apps. If I find a good solution I will submit an additional pull request.

**Comment by yakovkhalinsky** [comment]
Hi @obihann thank you very much for doing a PR for work I have been trying to make time for :+1: 

I'll merge this in and do some testing and then update the README and npm publish

**Comment by yakovkhalinsky** [comment]
Merging

**Comment by obihann** [comment]
Glad I could help.

**Pull request merged**
