### PR TITLE
Add support for running the server as Restify middleware

### PR DESCRIPTION
**Pull request by StefanoDalpiaz**
I have added some simple logic so that the middleware function can be used not only in Express, but also in Restify.

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Very interesting. Will have a look over this in the next couple days.

One question. Would you be able to contribute an example in this directory:
https://github.com/Aconex/drakov/tree/master/examples

Would help other users to see an implementation example :+1:

**Comment by StefanoDalpiaz** [comment]
Sure, I just added a new example file, which looks very similar to the Express one.

I also had to add a dependency to Restify, otherwise the example wouldn't run.

**Comment by tallpsmith** [comment]
@yakovkhalinsky would love to understand if you believe this one is worth pursuing still or not - 5 years on in the Javascript world is an eternity, so not sure how relevant this still is.

to the original author @StefanoDalpiaz - if you were able to review this too, and comment, and perhaps rebase/resolve conflicts if you think it's still worthwhile.

Many thanks (and apologise for the delays... 😬  )

**Comment by yakovkhalinsky** [comment]
My opinion on this is that while the intention is useful, I would rather not tie the app to any additional web frameworks.

We originally made the middleware function available to allow easy integration into existing Node.js apps that use express.

This would probably be better served as an external module that implements `drakov` as it's dependency.

There are however some changes not specific to restify that might be nice to include. Unfortunately these changes are now in conflict with newer changes.

Alas there are no supporting tests, so given the age unfortunately I think the safest thing to do next here is to close it and keep the branch.

**Comment by tallpsmith** [comment]
Based on the age of this PR (no fault of the original requestor though), and Yakov's comments.  I'm closing this MR.

If the original author is still interested and would like to revisit this, please raise a fresh one, with tests as Yakov indicated.  Thanks for your understanding.

**Pull request closed without merging**
