### PR TITLE
Substack pattern

### PR DESCRIPTION
**Pull request by kosmotaur**
Hi,

While trying to introduce new functionalities, we've found it more difficult than it could be to reuse logic. The code was relying on side effects, functions were sharing variables through JS scope and modules were fulfilling more than one responsibility, which has proven to be a significant hindrance.

This came about when we were working on a discoverability page, where we wanted to list all the API endpoints. We needed to share the `ROUTE_MAP` object across modules, but unfortunately it was deeply entangled in other logic.

Please consider this refactor, where pieces of logic are contained as a function in separate modules, AKA the Substack pattern.

Starting with f004806, we've been extracting code step by step. Every commit after passed tests and retained Drakov's functionality, so you could more easily follow our reasoning.

Kind regards,
@SiCurious and @kosmotaur

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Excellent PR :8ball: will definitely make it easier for the codebase going forward :+1:

**Comment by yakovkhalinsky** [comment]
Merging

**Comment by kosmotaur** [comment]
Thanks!

**Comment by yakovkhalinsky** [comment]
Thank you very much for the PR :+1: 

I'll bump the npm version and publish, shortly.

**Pull request merged**
