### PR TITLE
Support newer versions of node

### PR DESCRIPTION
**Pull request by ascripcaru**
Created based on https://github.com/Aconex/drakov/pull/107
Used a newer version of travis image (https://docs.travis-ci.com/user/trusty-ci-environment/) that has by default g++ 4.8 needed for node 4 and 5
Added travis tests on node 4 and 5

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Alright @ascripcaru let's do this :+1: 

@ascripcaru  can I assume that PR #107 is obsolete and can be closed?

**Comment by yakovkhalinsky** [comment]
Merging and will bump version to 0.2.0 shortly

**Comment by yakovkhalinsky** [comment]
Huge thanks to @ascripcaru, for a small yet very important PR :dancers: :dart:

**Comment by ascripcaru** [comment]
thanks @yakovkhalinsky for the new release. really needed that for my other projects. thanks a bunch

**Pull request merged**
